export { default as AddressInfo } from "./AddressInfo";
export { default as ContactForm } from "./ContactForm";
export { default as FAQComponent } from "./FAQ";
export { default as FooterPaymentAndRights } from "./FooterPaymentAndRights";
export { default as MainHeroWithFigure } from "./MainHeroWithFigure";
export { default as NewsletterComponent } from "./Newsletter";
export { default as PlansCarousel } from "./PlansCarousel";
export { default as ProductDifferentials } from "./ProductDifferentials";
export { default as ThreeDescriptiveCards } from "./ThreeDescriptiveCards";
